# @package _global_

defaults:
  - _self_
  - data: lf.yaml
  - model: lf.yaml
  - callbacks: null
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

  - experiment: null

task_name: "perturb"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
